// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models
{
    public partial class AutoHistoryCount
    {
        public string Id { get; set; }
        public int? Count { get; set; }
    }
}